import { Stagiaire } from './stagiaire';

export const STAGIAIRES: Stagiaire[] = [
  {
    id: '1',
    prenom: 'Charles',
    nom: 'Etienne',
    courriel: 'abc@ss.ca',
    competences: ['HTML ', 'Css '],
    formations: ['Cegep'],
    ville: 'Trois-Ri',
    telephone: '(819)-333-2345',
    messageMotivation: 'Tres motive',
    dateDebutStage: '2021-01-01',
  },
  {
    id: '2',
    prenom: 'Charlotte',
    nom: 'Etienne',
    courriel: 'abc@ss.ca',
    competences: ['HTML', 'Css'],
    formations: ['Cegep'],
    ville: 'Trois-Ri',
    telephone: '(819)-333-2345',
    messageMotivation: 'Tres motive',
    dateDebutStage: '2021-01-01',
  },
  {
    id: '3',
    prenom: 'Charlounne',
    nom: 'Etienne',
    courriel: 'abc@ss.ca',
    competences: ['HTML', 'Css'],
    formations: ['Cegep'],
    ville: 'Trois-Ri',
    telephone: '(819)-333-2345',
    messageMotivation: 'Tres motive',
    dateDebutStage: '2021-01-01',
  },
  {
    id: '4',
    prenom: 'Charlounne',
    nom: 'Etienne',
    courriel: 'abc@ss.ca',
    competences: ['HTML', 'Css'],
    formations: ['Cegep'],
    ville: 'Trois-Ri',
    telephone: '(819)-333-2345',
    messageMotivation: 'Tres motive',
    dateDebutStage: '2021-01-01',
  },
];
