import { Entreprise } from './entreprise';
import { OffreStage } from './offre-stage';

export const OFFRESSTAGE: OffreStage[] = [
  {
    _id: 'r',
    accepter: false,
    ville: 'fdsa',
    titre: 'Front-end React',
    dateDebut: '01-01-2021',
    dateFin: '01-03-2021',
    competencesRechercher: 'r',
    emploieApresStage: true,
    remuneration: 'oui',
    dateDeParution: '01-01-2020',
    description: 'lorem lorem',
    dureeStageSemaine: 2,
    typeDeStage: 'temps plein',
    informationSupplementaire: 'non',
    nombreHeuresSemaine: 25,
    entreprise: {
      _id: '1',
      courriel: 'sa',
      logo: 'dasdsa',
      nomResponsable: 'sasa',
      numeroTel: '31313',
      prenomResponsable: 'dsada',
      siteWeb: 'dasdasdsa',
      nomEntreprise: 'CGI',
      adresse: '123 ici',
      ville: 'Shawi',
      secteurActivite: ['ici', 'la'],
      aPropos: 'Bienvenito',
      nom: 'temporaire',
      motDePasse: 'dasda',
    },
    // },
    // {
    //   _id: 'ra',
    //   accepter: false,
    //   ville: 'fdsa',
    //   titre: 'Vue js dev',
    //   dateDebut: '01-01-2021',
    //   dateFin: '01-03-2021',
    //   competencesRechercher: ['r', 'r', 'r'],
    //   emploieApresStage: true,
    //   remuneration: true,
    //   dateDeParution: '01-01-2020',
    //   description: 'lorem lorem',
    //   nombreHeuresSemaine: 25,
    //   entreprise: {
    //     _id: '1',
    //     courriel: 'sa',
    //     logo: 'dasdsa',
    //     nomResponsable: 'sasa',
    //     numeroTel: '31313',
    //     prenomResponsable: 'dsada',
    //     siteWeb: 'dasdasdsa',
    //     nomEntreprise: 'CGI',
    //     adresse: '123 ici',
    //     ville: 'Shawi',
    //     secteurActivite: ['ici', 'la'],
    //     aPropos: 'Bienvenito',
    //     nom: 'temporaire',
    //     motDePasse: 'dasda',
    //   },
    // },
    // {
    //   _id: 'ra',
    //   titre: 'Vue js dev',
    //   dateDebut: '01-01-2021',
    //   accepter: false,
    //   ville: 'fdsa',
    //   dateFin: '01-03-2021',
    //   competencesRechercher: ['r', 'r', 'r'],
    //   emploieApresStage: true,
    //   remuneration: true,
    //   dateDeParution: '01-01-2020',
    //   description: 'lorem lorem',
    //   nombreHeuresSemaine: 25,
    //   entreprise: {
    //     _id: '1',
    //     courriel: 'sa',
    //     logo: 'dasdsa',
    //     nomResponsable: 'sasa',
    //     numeroTel: '31313',
    //     prenomResponsable: 'dsada',
    //     siteWeb: 'dasdasdsa',
    //     nomEntreprise: 'CGI',
    //     adresse: '123 ici',
    //     ville: 'Shawi',
    //     secteurActivite: ['ici', 'la'],
    //     aPropos: 'Bienvenito',
    //     nom: 'temporaire',
    //     motDePasse: 'dasda',
    //   },
    // },
    // {
    //   _id: 'ra',
    //   titre: 'Vue js dev',
    //   dateDebut: '01-01-2021',
    //   dateFin: '01-03-2021',
    //   competencesRechercher: ['r', 'r', 'r'],
    //   emploieApresStage: true,
    //   accepter: false,
    //   ville: 'fdsa',
    //   remuneration: true,
    //   dateDeParution: '01-01-2020',
    //   description: 'lorem lorem',
    //   nombreHeuresSemaine: 25,
    //   entreprise: {
    //     _id: '1',
    //     courriel: 'sa',
    //     logo: 'dasdsa',
    //     nomResponsable: 'sasa',
    //     numeroTel: '31313',
    //     prenomResponsable: 'dsada',
    //     siteWeb: 'dasdasdsa',
    //     nomEntreprise: 'CGI',
    //     adresse: '123 ici',
    //     ville: 'Shawi',
    //     secteurActivite: ['ici', 'la'],
    //     aPropos: 'Bienvenito',
    //     nom: 'temporaire',
    //     motDePasse: 'dasda',
    //   },
    // },
  },
];
