export const SECTEURSACTIVITE: string[] = [
  'Administrations publiques',
  'Agriculture, foresterie, pêche et chasse',
  'Arts, spectacles et loisirs',
  'Autres services (sauf les administrations publiques)',
  'Commerce de détail',
  'Commerce de gros',
  'Construction',
  'Extraction minière,  et extraction de pétrole et de gaz  ',
  'Fabrication',
  'Finance et assurances',
  'Gestion de sociétés et d’entreprises',
  'Hébergement et services de restauration',
  'Industrie de l’information et industrie culturelle',
  'Services administratifs, services de soutien, services de gestion des déchets et services d’assainissement',
  'Services d’enseignement',
  'Services de restauration et débit de boisson',
  'Services immobiliers et services de location',
  'Services professionnels, scientifiques et techniques',
  'Services publics',
  'Soins de santé et assistance sociale',
  'Transport et entreposage',
  'Transport par camion',
];
