import { Entreprise } from './entreprise';
import { OffreStage } from './offre-stage';

export const OFFRESSTAGE: OffreStage[] = [
  {
    id: 'r',
    titre: 'Front-end React',
    dateDebut: '01-01-2021',
    dateFin: '01-03-2021',
    competencesRechercher: ['r', 'r', 'r'],
    emploieApresStage: true,
    remuneration: true,
    dateDeParution: '01-01-2020',
    description: 'lorem lorem',
    nombreHeuresSemaine: 25,
    entreprise: {
      id: '1',
      nom: 'CGI',
      adresse: '123 ici',
      ville: 'Shawi',
      secteurActivite: ['ici', 'la'],
      aPropos: 'Bienvenito',
    },
  },
  {
    id: 'ra',
    titre: 'Vue js dev',
    dateDebut: '01-01-2021',
    dateFin: '01-03-2021',
    competencesRechercher: ['r', 'r', 'r'],
    emploieApresStage: true,
    remuneration: true,
    dateDeParution: '01-01-2020',
    description: 'lorem lorem',
    nombreHeuresSemaine: 25,
    entreprise: {
      id: '2',
      nom: 'Desjardins',
      adresse: '321 ici',
      ville: 'Quebec',
      secteurActivite: ['ici', 'la'],
      aPropos: 'Bienvenito',
    },
  },
  {
    id: 'ra',
    titre: 'Vue js dev',
    dateDebut: '01-01-2021',
    dateFin: '01-03-2021',
    competencesRechercher: ['r', 'r', 'r'],
    emploieApresStage: true,
    remuneration: true,
    dateDeParution: '01-01-2020',
    description: 'lorem lorem',
    nombreHeuresSemaine: 25,
    entreprise: {
      id: '2',
      nom: 'Desjardins',
      adresse: '321 ici',
      ville: 'Quebec',
      secteurActivite: ['ici', 'la'],
      aPropos: 'Bienvenito',
    },
  },
  {
    id: 'ra',
    titre: 'Vue js dev',
    dateDebut: '01-01-2021',
    dateFin: '01-03-2021',
    competencesRechercher: ['r', 'r', 'r'],
    emploieApresStage: true,
    remuneration: true,
    dateDeParution: '01-01-2020',
    description: 'lorem lorem',
    nombreHeuresSemaine: 25,
    entreprise: {
      id: '2',
      nom: 'Desjardins',
      adresse: '321 ici',
      ville: 'Quebec',
      secteurActivite: ['ici', 'la'],
      aPropos: 'Bienvenito',
    },
  },
];
