import { Stagiaire } from './stagiaire';

export const STAGIAIRES: Stagiaire[] = [
  // {
  //   _id: '1',
  //   prenom: 'Charles',
  //   nom: 'Etienne',
  //   courriel: 'abc@ss.ca',
  //   competences: ['HTML ', 'Css '],
  //   formations: 'Vue',
  //   ville: 'Trois-Ri',
  //   telephone: '(819)-333-2345',
  //   messageMotivation: 'Tres motive',
  //   dateDebutStage: '2021-01-01',
  // },
  // {
  //   _id: '2',
  //   prenom: 'Charlotte',
  //   nom: 'Etienne',
  //   courriel: 'abc@ss.ca',
  //   competences: ['HTML', 'Css'],
  //   formations: 'React',
  //   ville: 'Trois-Ri',
  //   telephone: '(819)-333-2345',
  //   messageMotivation: 'Tres motive',
  //   dateDebutStage: '2021-01-01',
  // },
  // {
  //   _id: '3',
  //   prenom: 'Charlounne',
  //   nom: 'Etienne',
  //   courriel: 'abc@ss.ca',
  //   competences: ['HTML', 'Css'],
  //   formations: 'Angular',
  //   ville: 'Trois-Ri',
  //   telephone: '(819)-333-2345',
  //   messageMotivation: 'Tres motive',
  //   dateDebutStage: '2021-01-01',
  // },
  // {
  //   _id: '4',
  //   prenom: 'Charlounne',
  //   nom: 'Etienne',
  //   courriel: 'abc@ss.ca',
  //   competences: ['HTML', 'Css'],
  //   formations: 'Node.js',
  //   ville: 'Trois-Ri',
  //   telephone: '(819)-333-2345',
  //   messageMotivation: 'Tres motive',
  //   dateDebutStage: '2021-01-01',
  // },
];
